version: "3.9"
services:
  api:
    build:
      dockerfile: "./Dockerfiles/Api_Dockerfile.yml"
    ports:
      - "60106:8031"
    restart: always
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: "api_test"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "60105:5432"